name: CI/CD Pipeline

on:
  push:
    branches:
      - master # Mengubah dari `master` ke `main` sesuai standar baru

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest # Menggunakan variabel env

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: sidiq_muhamadtoha
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Masuk ke direktori proyek di server
            cd /home/sidiq_muhamadtoha/dev-ops-learning/hello-world
            
            # Login ke GitHub Packages menggunakan token
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Tarik image terbaru dari GitHub Packages
            docker compose pull app
            
            # Jalankan kembali kontainer dengan image terbaru
            docker compose up -d
            
            # Opsional: Membersihkan image lama yang tidak digunakan
            docker image prune -f
