name: CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          push: true
          # Menggunakan fungsi toLower di sini
          tags: ${{ env.REGISTRY }}/${{ toLower(github.repository) }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: sidiq_muhamadtoha
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/sidiq_muhamadtoha/dev-ops-learning/hello-world
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Menggunakan toLower di sini juga
            docker compose pull ghcr.io/${{ toLower(github.repository) }}:latest
            docker compose up -d
            docker image prune -f
